server:
  dev:
    enabled: false
  standalone:
    enabled: true
  dataStorage:
    enabled: true
    storageClass: local-storage
    size: 500Mi
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: vvault.aliien.uk
    tls:
      - secretName: aliien-uk-tls
        hosts:
          - vvault.aliien.uk

injector:
  enabled: true
  replicas: 1
  image:
    repository: hashicorp/vault-k8s
    tag: 1.7.5
  agentImage:
    repository: hashicorp/vault
    tag: 2.0.3
