# Development Environment Configuration
frontend-service:
  replicaCount: 1
  ingress:
    enabled: true
    host: vapp.aliien.uk
    tls: true
    tlsSecretName: aliien-uk-tls
  resources:
    limits:
      cpu: 150m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

backend-service:
  replicaCount: 1
  ingress:
    enabled: true
    host: vapi.aliien.uk
    tls: true
    tlsSecretName: aliien-uk-tls
  vault:
    enabled: true
    secretPath: secret/data/dev/database
  env:
    logLevel: DEBUG

db-service:
  persistence:
    size: 2Gi

backup-service:
  persistence:
    size: 10Gi

redis-service:
  replicaCount: 1
