replicaCount: 2

image:
  repository: vharbor.aliien.uk/pro4/mypro-frontend
  tag: "e8d0e0fd30cd2a1a911cf65953e8269cedcb54aa"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-pull-secret

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  host: vapp.aliien.uk
  tls: true
  tlsSecretName: aliien-uk-tls

env:
  backendUrl: "http://app-mypro-dev-backend-service:5000"
  port: "3000"
  timeoutMs: "5000"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 1

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
