# Prometheus, Grafana, Node Exporter, cAdvisor Stack Configuration
defaultRules:
  create: true

nodeExporter:
  enabled: true
  operatingSystem: linux

kubelet:
  enabled: true
  serviceMonitor:
    cAdvisor: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  enabled: true
  adminPassword: "admin"
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - vgrafana.aliien.uk
    tls:
      - hosts:
          - vgrafana.aliien.uk
        secretName: aliien-uk-tls
  persistence:
    enabled: true
    size: 5Gi
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-stack.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false

alertmanager:
  enabled: true
  alertmanagerSpec:
    retention: 120h
