apiVersion: v2
name: umbrella-app
description: Master Enterprise Umbrella Chart binding Frontend, Backend, Database, and Cache
type: application
version: 2.0.0
appVersion: "2.0.0"

dependencies:
  - name: frontend-service
    version: 2.0.0
    repository: "file://../frontend-service"
  - name: backend-service
    version: 2.0.0
    repository: "file://../backend-service"
  - name: db-service
    version: 2.0.1
    repository: "file://../db-service"
  - name: redis-service
    version: 2.0.0
    repository: "file://../redis-service"
  - name: backup-service
    version: 2.0.0
    repository: "file://../backup-service"
