apiVersion: v2
name: backend-service
description: Helm chart for Flask v2 REST API Backend Service with Vault Secret Injection
type: application
version: 2.0.0
appVersion: "a656f4500f6b726a7e846dffec9a9104e720bf36"
