apiVersion: v2
name: backend-service
description: Helm chart for Flask v2 REST API Backend Service with Vault Secret Injection
type: application
version: 2.0.0
appVersion: "b2b5a6eee21929dcc81291b71b4119df2f1844ae"
