apiVersion: v2
name: backend-service
description: Helm chart for Flask v2 REST API Backend Service with Vault Secret Injection
type: application
version: 2.0.0
appVersion: "45a70c37240cb9c1db619e16f90a651598673598"
