auth:
  rootUser: admin

persistence:
  enabled: true
  storageClass: local-storage
  size: 1Gi

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: vminio.aliien.uk
  tls:
    - hosts:
        - vminio.aliien.uk
      secretName: aliien-uk-tls
