apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-frontend-dev
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: https://vapp.aliien.uk
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev-project
  source:
    repoURL: https://github.com/LubnaIbrahimMU/imagine-local-stack.git
    targetRevision: HEAD
    path: helm/charts/frontend-service
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations
