apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-mypro-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LubnaIbrahimMU/imagine-local-stack.git

    targetRevision: HEAD
    path: helm/charts/umbrella-app
    helm:
      valueFiles:
        - ../../values/values-dev.yml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
