apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mypro-backup-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev-project
  source:
    repoURL: https://github.com/LubnaIbrahimMU/imagine-local-stack.git
    targetRevision: HEAD
    path: helm/charts/backup-service
    helm:
      releaseName: app-mypro-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
