apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mypro-prd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: prd-project
  source:
    repoURL: 'https://github.com/your-org/mypro.git'
    targetRevision: HEAD
    path: helm/charts/umbrella-app
    helm:
      valueFiles:
        - ../../values/values-prd.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
