mysql:
  image: vharbor.aliien.uk/pro4/mypro-backup:"45a70c37240cb9c1db619e16f90a651598673598"
  existingSecret: mypro-dev-db-secret

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

backupCronJob:
  enabled: true
  schedule: "0 */6 * * *"
  image: vharbor.aliien.uk/pro4/mypro-backup:"45a70c37240cb9c1db619e16f90a651598673598"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

podDisruptionBudget:
  enabled: true
  minAvailable: 1
