mysql:
  image: mysql:8.0
  existingSecret: mypro-dev-db-secret

imagePullSecrets:
  - name: harbor-pull-secret

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

backupCronJob:
  enabled: true
  schedule: "0 */6 * * *"
  image: vharbor.aliien.uk/pro4/mypro-backup:febef99fd996b3f270676a2953bcfea9851ebcbf

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

podDisruptionBudget:
  enabled: true
  minAvailable: 1
