mysql:
  image: vharbor.aliien.uk/pro4/mypro-backup:"354aac1651db82e54fa77a8fe3c2e6242be04714"
  existingSecret: mypro-dev-db-secret

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

backupCronJob:
  enabled: true
  schedule: "0 */6 * * *"
  image: vharbor.aliien.uk/pro4/mypro-backup:"354aac1651db82e54fa77a8fe3c2e6242be04714"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

podDisruptionBudget:
  enabled: true
  minAvailable: 1
