mysql:
  image: vharbor.aliien.uk/pro4/mypro-backup:"c6a138a86c601c9baf8c0a455bb68e9bb0712527"
  existingSecret: mypro-dev-db-secret

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

backupCronJob:
  enabled: true
  schedule: "0 */6 * * *"
  image: vharbor.aliien.uk/pro4/mypro-backup:"c6a138a86c601c9baf8c0a455bb68e9bb0712527"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

podDisruptionBudget:
  enabled: true
  minAvailable: 1
