---
harbor_project_name: "{{ harbor_config.project_name | default('') }}"
harbor_local_registry: "{{ harbor_config.local_registry | default('', true) }}"
harbor_images: "{{ harbor_config.images | default([]) }}"
