# yaml-language-server: $schema=none
expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: aliien-uk-tls
  ingress:
    hosts:
      core: vharbor.aliien.uk
    controller: default
    className: nginx
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"

externalURL: https://vharbor.aliien.uk


persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      storageClass: local-storage
      size: 1Gi
    chartmuseum:
      storageClass: local-storage
      size: 500Mi
    jobservice:
      storageClass: local-storage
      size: 500Mi
    database:
      storageClass: local-storage
      size: 500Mi
    redis:
      storageClass: local-storage
      size: 256Mi
