apiVersion: v1
kind: Secret
metadata:
  name: repo-imagine-local-stack
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/LubnaIbrahimMU/imagine-local-stack.git
  username: LubnaIbrahimMU
  password: "${GITHUB_TOKEN}"
