apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.15.x
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/LubnaIbrahimMU/imagine-local-stack/main/infrastructure/harbor/harbor-values.yml


  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
