apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.min.io/
      chart: minio
      targetRevision: 5.0.x
      helm:
        valueFiles:
          - $values/infrastructure/minio/minio-values.yml
    - repoURL: https://github.com/LubnaIbrahimMU/imagine-local-stack.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
