apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.0.x
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/LubnaIbrahimMU/imagine-local-stack/main/infrastructure/minio/minio-values.yml


  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
