apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.0.x
    helm:
      values: |
        mode: standalone
        replicas: 1
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
        auth:
          rootUser: admin
        persistence:
          enabled: true
          storageClass: local-storage
          size: 1Gi
        ingress:
          enabled: true
          ingressClassName: nginx
          hostname: vminio.aliien.uk
          tls:
            - hosts:
                - vminio.aliien.uk
              secretName: aliien-uk-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
