apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.28.x
      helm:
        valueFiles:
          - $values/infrastructure/vault/vault-values.yml
    - repoURL: https://github.com/LubnaIbrahimMU/imagine-local-stack.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
