apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    app.kubernetes.io/name: db-service
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  db-root-password: {{ .Values.mysql.rootPassword | quote }}
  db-password: {{ .Values.mysql.password | quote }}
  db-user: {{ .Values.mysql.user | quote }}
  db-name: {{ .Values.mysql.database | quote }}
