apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-db-standby
  labels:
    app.kubernetes.io/name: db-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: standby
spec:
  serviceName: {{ .Release.Name }}-db-standby
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: db-service
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: standby
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db-service
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: standby
    spec:
      containers:
        - name: mysql-standby
          image: "{{ .Values.mysql.image }}"
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: db-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: db-name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: db-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: db-password
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 25
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]

            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: standby-data
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: {{ .Release.Name }}-db-init-sql
  volumeClaimTemplates:
    - metadata:
        name: standby-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
