image:
  repository: vharbor.aliien.uk/pro4/mypro-backup
  tag: "a568331efb7594eeb397ccccfccd1887b7d337ee"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-pull-secret

schedule: "0 */6 * * *"
database:
  host: app-mypro-dev-db-primary
  secretName: mypro-dev-db-secret

persistence:
  size: 10Gi
  storageClass: ""
