image:
  repository: vharbor.aliien.uk/pro4/mypro-backup
  tag: "3049e904af4987ea8865284be9aeafe00766d84b"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-pull-secret

schedule: "0 */6 * * *"
database:
  host: app-mypro-dev-db-primary
  secretName: mypro-dev-db-secret

persistence:
  size: 10Gi
  storageClass: ""
