image:
  repository: vharbor.aliien.uk/pro4/mypro-backup
  tag: "706bfe2381428981bf9ae9e5fdc0adae625e3c99"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-pull-secret

schedule: "0 */6 * * *"
database:
  host: app-mypro-dev-db-primary
  secretName: mypro-dev-db-secret

persistence:
  size: 10Gi
  storageClass: ""
